//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Venus
//  @ File Name : AbVenusBackendFactory.cs
//  @ Date : 2013/11/12
//  @ Author : Xavier Yin
//
//

using MainApplication.LogicLayer.Backend.PrintingModule;

namespace MainApplication.PresentationLayer.BackendSubsystemFactory
{
    /// <summary>
    /// 使用者介面存取後端服務的抽象類別產生工廠
    /// </summary>
    public abstract class AbVenusBackendFactory
    {
        /// <summary>
        /// 產生列印物件的方法
        /// </summary>
        /// <param name="printingModuleName"></param>
        /// <returns></returns>
        public abstract AbPrintingModule createPrintingModuleMethod(int printingModuleName);
    }
}
