//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Venus
//  @ File Name : PrintingModuleFactoryImp.cs
//  @ Date : 2013/11/12
//  @ Author : Xavier Yin
//
//

using MainApplication.LogicLayer.Backend.PrintingModule;

using System.IO;

namespace MainApplication.PresentationLayer.BackendSubsystemFactory
{
    /// <summary>
    /// 使用者介面存取後端服務的列印模組工廠實作類別
    /// </summary>
    public class PrintingModuleFactoryImp : AbVenusBackendFactory
    {
        private AbPrintingModule printingModule;

        /// <summary>
        /// 產生Venus專案的後端列印模組方法實作
        /// </summary>
        /// <param name="printingModuleName"></param>
        /// <returns></returns>
        public override AbPrintingModule createPrintingModuleMethod(int printingModuleName)
        {
            if (printingModuleName.Equals(0))
            {
                this.printingModule = new VenusPrintingModuleImp();
            }

            return this.printingModule;
        }
    }
}
