//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Venus
//  @ File Name : IPrintingModule.cs
//  @ Date : 2013/11/12
//  @ Author : Xavier Yin
//
//

using System.Drawing.Printing;
using System.Windows.Forms;
using System.Drawing;
using System;

namespace MainApplication.LogicLayer.Backend.PrintingModule
{
    /// <summary>
    /// 列印功能的抽象類別
    /// </summary>
    public abstract class AbPrintingModule
    {
        protected PrintDocument printDocument1;
        protected PrintPreviewDialog printPreviewDialog1;
        protected PrintDialog printDialog1;
        protected PageSetupDialog pageSetupDialog1;
        protected TextBox textBox1;

        /// <summary>
        /// 列印功能建構子
        /// </summary>
        public AbPrintingModule() { }

        /// <summary>
        /// 提供前端使用者介面設定列印控制項
        /// </summary>
        /// <param name="printDocument1"></param>
        /// <param name="printPreviewDialog1"></param>
        /// <param name="printDialog1"></param>
        /// <param name="pageSetupDialog1"></param>
        /// <param name="textBox1"></param>
        public void setParameters(PrintDocument printDocument1, PrintPreviewDialog printPreviewDialog1, PrintDialog printDialog1, PageSetupDialog pageSetupDialog1, TextBox textBox1)
        {
            this.printDocument1 = printDocument1;                 
            this.printPreviewDialog1 = printPreviewDialog1;        
            this.printDialog1 = printDialog1;                     
            this.pageSetupDialog1 = pageSetupDialog1;              
            this.textBox1 = textBox1;                              
            this.printDocument1.PrintPage += new System.Drawing.Printing.PrintPageEventHandler(this.printDocument1_PrintPage);

            printPreviewDialog1.Document = printDocument1;
            printDialog1.Document = printDocument1;
            pageSetupDialog1.Document = printDocument1;
            textBox1.ScrollBars = ScrollBars.Both;
            textBox1.Font = new Font("標楷體", 12, FontStyle.Regular);
        }

        /// <summary>
        /// 列印功能回呼函式
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        protected void printDocument1_PrintPage(object sender, System.Drawing.Printing.PrintPageEventArgs e)
        {
            Graphics prnGraph = e.Graphics;
            Font prnFont = new Font(textBox1.Font.Name, textBox1.Font.Size, textBox1.Font.Style);
            SolidBrush prnBrush = new SolidBrush(textBox1.ForeColor);
            Single left = printDocument1.DefaultPageSettings.Margins.Left - 10;
            Single top = printDocument1.DefaultPageSettings.Margins.Top - 20;
            prnGraph.DrawString(textBox1.Text, prnFont, prnBrush, left, top);
        }

        /// <summary>
        /// 列印操作
        /// </summary>
        public abstract void print();

        /// <summary>
        /// 預覽列印操作
        /// </summary>
        public abstract void preview();

        /// <summary>
        /// 設定頁面操作
        /// </summary>
        public abstract void setPageLayot();

        /// <summary>
        /// 為了廠商設定自己的列印組態操作
        /// </summary>
        public abstract void setPrintintConfigLayout();
    }
}
