//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Venus
//  @ File Name : VenusPrintingModuleImp.cs
//  @ Date : 2013/11/12
//  @ Author : 
//
//

using System;
using System.Windows.Forms;

namespace MainApplication.LogicLayer.Backend.PrintingModule
{
    /// <summary>
    /// Venus列印函式實作類別
    /// </summary>
    public class VenusPrintingModuleImp : AbPrintingModule
    {
        public override void print()
        {
            if (printDialog1.ShowDialog() == DialogResult.OK)
            {
                printDocument1.Print();
            }
        }

        public override void preview()
        {
            printPreviewDialog1.ShowDialog();
        }

        public override void setPageLayot()
        {
            if (pageSetupDialog1.ShowDialog() == DialogResult.OK)
            {
                printDocument1.DefaultPageSettings =
                    pageSetupDialog1.PageSettings;
            }
        }

        public override void setPrintintConfigLayout()
        {
            throw new NotImplementedException();
        }
    }
}
